//
// Generated file, do not edit! Created by opp_msgtool 6.2 from src/cluster/ClusterHeader.msg.
//

#ifndef __CLUSTERHEADER_M_H
#define __CLUSTERHEADER_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0602
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class ClusterHeader;
#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

/**
 * Class generated from <tt>src/cluster/ClusterHeader.msg:4</tt> by opp_msgtool.
 * <pre>
 * class ClusterHeader extends inet::FieldsChunk
 * {
 *     int kind;          // 0=HELLO, 1=CH_REQUEST, 2=CH_RESPONSE, 3=DECLARATION
 *     int srcId;         // sender node index
 *     int dstId;         // -1=broadcast, otherwise target node index
 *     int clusterHeadId; // CH id (or -1)
 *     double utility;    // sender’s cluster utility
 *     double hldTime;    // sender’s link-holding-time metric
 * }
 * </pre>
 */
class ClusterHeader : public ::inet::FieldsChunk
{
  protected:
    int kind = 0;
    int srcId = 0;
    int dstId = 0;
    int clusterHeadId = 0;
    double utility = 0;
    double hldTime = 0;

  private:
    void copy(const ClusterHeader& other);

  protected:
    bool operator==(const ClusterHeader&) = delete;

  public:
    ClusterHeader();
    ClusterHeader(const ClusterHeader& other);
    virtual ~ClusterHeader();
    ClusterHeader& operator=(const ClusterHeader& other);
    virtual ClusterHeader *dup() const override {return new ClusterHeader(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getKind() const;
    virtual void setKind(int kind);

    virtual int getSrcId() const;
    virtual void setSrcId(int srcId);

    virtual int getDstId() const;
    virtual void setDstId(int dstId);

    virtual int getClusterHeadId() const;
    virtual void setClusterHeadId(int clusterHeadId);

    virtual double getUtility() const;
    virtual void setUtility(double utility);

    virtual double getHldTime() const;
    virtual void setHldTime(double hldTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ClusterHeader& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ClusterHeader& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline ClusterHeader *fromAnyPtr(any_ptr ptr) { return check_and_cast<ClusterHeader*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __CLUSTERHEADER_M_H

