[General]
repeat = 5
network = src.AdhocNetwork1
sim-time-limit = 50s

*.host[*].ipv4.arp.typename = "GlobalArp"
*.host[*].numApps = 3
*.host[*].app[0].typename = "src.cluster.ClusterApp"
*.host[*].app[0].localPort = 4000
*.host[*].app[0].destPort  = 4000
*.host[*].app[0].helloInterval = 1s
*.host[*].app[0].cfInterval    = 3s
*.host[*].app[0].hldTimeThreshold = 1s
*.host[*].app[0].maxTrials = 3
*.host[*].app[0].requestTimeout = 1s
*.host[*].app[0].maxClusterSize = 10
*.host[*].app[0].statsInterval = 1s

#*.host[*].app[1].typename = "TcpBasicClientApp" 
*.host[*].app[1].typename = "src.tcp.RecordingTcpClientApp"
*.host[*].app[1].delaySamplePeriod = 1s
*.host[*].app[1].delayStaleWindow  = 3s
*.host[*].app[1].connectPort = 1000
*.host[*].app[1].tOpen = uniform(1s, 2s)
*.host[*].app[1].tSend = uniform(1s, 2s)
*.host[*].app[1].thinkTime = uniform(0s, 1s)
*.host[*].app[1].idleInterval = uniform(3s, 5s)
*.host[*].app[1].sendBytes = 200B
*.host[*].app[1].sendInterval = uniform(1s, 2s)
*.host[*].app[1].connectAddress = "host[" + string((index + intuniform(1,99)) % 100) + "]"

*.host[*].app[2].typename = "TcpEchoApp"
*.host[*].app[2].localPort = 1000

*.host[*].typename = "RouterWithMetrics"
**.metrics.samplePeriod = 0.5s
**.metrics.recordPerUtility = true
*.host[*].wlan[0].typename = "WirelessInterface"

##UnitDisk
#*.host[*].wlan[0].radio.transmitter.communicationRange = 350m
#*.host[*].wlan[0].radio.receiver.ignoreInterference = false
#*.host[*].wlan[0].radio.transmitter.interferenceRange = 400m
#*.host[*].wlan[0].radio.typename = "UnitDiskRadio"


## ApskScalarRadio
#*.radioMedium.typename = "ApskScalarRadioMedium"
#*.host[*].wlan[0].radio.typename = "ApskScalarRadio"
#*.radioMedium.backgroundNoise.power = -120dBm
#*.host[*].wlan[0].radio.transmitter.power = 20mW
#*.host[*].wlan[0].radio.transmitter.centerFrequency = 2.412GHz
#*.host[*].wlan[0].radio.transmitter.bandwidth = 20MHz
#*.host[*].wlan[0].radio.transmitter.energyDetection = -90dBm
#*.host[*].wlan[0].radio.transmitter.bitrate = 6Mbps
#*.host[*].wlan[0].radio.transmitter.preambleDuration = 16us
#*.host[*].wlan[0].radio.transmitter.headerLength = 16b
#*.host[*].wlan[0].radio.receiver.sensitivity = -82dBm
#*.host[*].wlan[0].radio.receiver.snirThreshold = 4dB
#*.host[*].wlan[0].radio.receiver.centerFrequency = 2.412GHz
#*.host[*].wlan[0].radio.receiver.bandwidth = 20MHz
#*.host[*].wlan[0].radio.receiver.energyDetection = -90dBm
#*.host[*].wlan[0].radio.centerFrequency = 2.412GHz
#*.host[*].wlan[0].radio.bandwidth = 20MHz
#*.host[*].wlan[0].radio.energyDetection = -90dBm
#*.radioMedium.analogModel.ignorePartialInterference = true

## ApskDimensionalRadio
#*.radioMedium.typename = "ApskDimensionalRadioMedium"
#*.radioMedium.analogModel.typename = "DimensionalAnalogModel"
#*.radioMedium.backgroundNoise.power = -120dBm
#*.host[*].wlan[0].radio.typename = "ApskDimensionalRadio"
#*.host[*].wlan[0].radio.transmitter.power = 20mW
#*.host[*].wlan[0].radio.transmitter.centerFrequency = 2.412GHz
#*.host[*].wlan[0].radio.transmitter.bandwidth = 20MHz
#*.host[*].wlan[0].radio.transmitter.energyDetection = -90dBm
#*.host[*].wlan[0].radio.transmitter.bitrate = 6Mbps
#*.host[*].wlan[0].radio.transmitter.preambleDuration = 16us
#*.host[*].wlan[0].radio.transmitter.headerLength = 16b
#*.host[*].wlan[0].radio.receiver.sensitivity = -82dBm
#*.host[*].wlan[0].radio.receiver.snirThreshold = 4dB
#*.host[*].wlan[0].radio.receiver.centerFrequency = 2.412GHz
#*.host[*].wlan[0].radio.receiver.bandwidth = 20MHz
#*.host[*].wlan[0].radio.receiver.energyDetection = -90dBm
#*.host[*].wlan[0].radio.centerFrequency = 2.412GHz
#*.host[*].wlan[0].radio.bandwidth = 20MHz
#*.host[*].wlan[0].radio.energyDetection = -90dBm

##Ieee80211ScalarRadio
#*.radioMedium.typename = "Ieee80211ScalarRadioMedium"
#*.host[*].wlan[0].radio.typename = "Ieee80211ScalarRadio"
#*.host[*].wlan[0].radio.transmitter.power = 20mW
#*.host[*].wlan[0].radio.transmitter.centerFrequency = 2.412GHz
#*.host[*].wlan[0].radio.transmitter.bandwidth = 20MHz
#*.host[*].wlan[0].radio.receiver.sensitivity = -82dBm
#*.host[*].wlan[0].radio.receiver.snirThreshold = 4dB
#*.host[*].wlan[0].radio.opMode = "g(mixed)"
#*.host[*].wlan[0].radio.transmitter.bitrate = 6Mbps
#*.host[*].wlan[0].radio.centerFrequency = 2.412GHz
#*.host[*].wlan[0].radio.bandwidth = 5MHz
#*.radioMedium.backgroundNoise.power = -120dBm
#*.host[*].wlan[0].radio.transmitter.preambleDuration = 16us
#*.host[*].wlan[0].radio.transmitter.headerLength = 16b
#*.host[*].wlan[0].radio.receiver.energyDetection = -90dBm

# IEEE 802.11 + Dimensional PHY
*.radioMedium.typename = "Ieee80211DimensionalRadioMedium"
*.radioMedium.analogModel.typename = "DimensionalAnalogModel"
*.radioMedium.backgroundNoise.power = -120dBm
*.host[*].wlan[0].radio.typename = "Ieee80211DimensionalRadio"
*.host[*].wlan[0].radio.transmitter.power = 2mW
*.host[*].wlan[0].radio.transmitter.centerFrequency = 2.412GHz
*.host[*].wlan[0].radio.transmitter.bandwidth = 20MHz
*.host[*].wlan[0].radio.receiver.sensitivity = -90dBm
*.host[*].wlan[0].radio.receiver.snirThreshold = 4dB
*.host[*].wlan[0].radio.receiver.ignoreInterference = false
*.host[*].wlan[0].mac.rateControl.typename = "ConstantRateControl"
*.host[*].wlan[0].mac.rateControl.dataRate = 6Mbps
*.host[*].wlan[0].mac.rateControl.multicastRate = 6Mbps

# non-persistent CSMA
#*.host[*].wlan[0].mac.typename = "CsmaCaMac"
#*.host[*].wlan[0].mac.fullDuplex = false
#*.host[*].wlan[0].mac.useBackoff = true
#*.host[*].wlan[0].mac.useAck = false
#*.host[*].wlan[0].mac.useRtsCts = false


#CSMA/CA 
#*.host[*].wlan[0].mac.typename = "CsmaCaMac"
#*.host[*].wlan[0].mac.fullDuplex = false
#*.host[*].wlan[0].mac.useBackoff = true
#*.host[*].wlan[0].mac.useAck = false
#*.host[*].wlan[0].mac.useRtsCts = true

#CSMA/CA/ACK
*.host[*].wlan[0].mac.typename = "CsmaCaMac"
*.host[*].wlan[0].mac.ackTimeout = 300us
*.host[*].wlan[0].mac.useAck = true
*.host[*].wlan[0].mac.fullDuplex = false
*.host[*].wlan[0].mac.headerLength = 23B

# B-MAC
#*.host[*].wlan[0].mac.typename = "BMac"
#*.host[*].wlan[0].mac.headerLength = 1B
#*.host[*].wlan[0].mac.slotDuration = 0.025s


# X-MAC
#*.host[*].wlan[0].mac.typename = "XMac"
#*.host[*].wlan[0].mac.headerLength = 24B
#*.host[*].wlan[0].mac.slotDuration = 0.1s
#*.host[*].wlan[0].mac.useMACAcks = true

#BonnMobility
#*.host[*].mobility.typename = "BonnMotionMobility"
#*.host[*].mobility.traceFile = "bonnmotion.movements"
#*.host[*].mobility.is3D = false 
#*.host[*].mobility.nodeId = -1

#RandomWaypoint
*.host[*].mobility.typename = "RandomWaypointMobility"
*.host[*].mobility.speed = 10mps
*.host[*].mobility.waitTime = 100ms

# CircleMobility (radius 250m)
#*.host[*].mobility.typename = "CircleMobility"
#*.host[*].mobility.cx = 625m
#*.host[*].mobility.cy = 625m
#*.host[*].mobility.r = (parentIndex() % 2 == 0) ? 500m : 250m
#*.host[*].mobility.startAngle =
#    (parentIndex() % 2 == 0)
#      ? (360deg * int(parentIndex() / 2) / int((25 + 1) / 2))
#      : (360deg * int(parentIndex() / 2) / int(25 / 2))
#*.host[*].mobility.speed = 10mps


#LinearMobility
#*.host[*].mobility.typename = "LinearMobility"
#*.host[*].mobility.speed = 10mps
#*.host[*].mobility.angle = 45deg

#GaussMarkov
#*.host[*].mobility.typename = "GaussMarkovMobility"
#*.host[*].mobility.alpha = 0.7
#*.host[*].mobility.speed = uniform(5mps, 10mps)
#*.host[*].mobility.speedStdDev = 1mps
#*.host[*].mobility.angle = uniform(0deg, 360deg)
#*.host[*].mobility.angleStdDev = 10deg
#*.host[*].mobility.margin = 2m
#
*.host[*].wlan[0].queue.typename = "DropTailQueue"
*.host[*].wlan[0].queue.packetCapacity = 10

*.host[*].hasStatus = true
*.host[*].wlan[0].radio.energyConsumer.typename = "StateBasedEpEnergyConsumer"
*.host[*].wlan[0].radio.energyConsumer.offPowerConsumption = 0mW
*.host[*].wlan[0].radio.energyConsumer.sleepPowerConsumption = 1mW
*.host[*].wlan[0].radio.energyConsumer.switchingPowerConsumption = 1mW
*.host[*].wlan[0].radio.energyConsumer.receiverIdlePowerConsumption = 2mW
*.host[*].wlan[0].radio.energyConsumer.receiverBusyPowerConsumption = 5mW
*.host[*].wlan[0].radio.energyConsumer.receiverReceivingPowerConsumption = 10mW
*.host[*].wlan[0].radio.energyConsumer.transmitterIdlePowerConsumption = 2mW
*.host[*].wlan[0].radio.energyConsumer.transmitterTransmittingPowerConsumption = 100mW
*.host[*].energyStorage.typename = "SimpleEpEnergyStorage"
*.host[*].energyStorage.nominalCapacity = 2J # maximum capacity
*.host[*].energyStorage.initialCapacity = 2J
*.host[*].energyManagement.typename = "SimpleEpEnergyManagement"
*.host[*].energyManagement.nodeStartCapacity = 0.0001J # start threshold
*.host[*].energyManagement.nodeShutdownCapacity = 0.0001J # shutdown threshold

#*.host[*].**.bitrate = 1Mbps
*.host[*].**.bitrate = 6Mbps
*.host[*].forwarding = true

*.host[*].mobility.constraintAreaMinX = 0m
*.host[*].mobility.constraintAreaMinY = 0m
*.host[*].mobility.constraintAreaMinZ = 0m
*.host[*].mobility.constraintAreaMaxX = 1250m
*.host[*].mobility.constraintAreaMaxY = 1250m
*.host[*].mobility.constraintAreaMaxZ = 0m
*.host[*].mobility.initialX = uniform(100m, 1150m)
*.host[*].mobility.initialY = uniform(100m, 1150m)
*.host[*].wlan[0].radio.displayCommunicationRange = true
#*.host[*].wlan[0].radio.displayCommunicationRange = true
#*.host[*].wlan[0].radio.displayInterferenceRange = true

*.configurator.config = xml("<config><interface hosts='**' address='10.0.0.x' netmask='255.255.255.0'/></config>")
*.configurator.addDefaultRoutes = false
*.configurator.addStaticRoutes = false
*.configurator.optimizeRoutes = false
*.host*.ipv4.routingTable.netmaskRoutes = ""

*.linkVisualizer.*.displayLinks = false
# *.visualizer.*.displayTransportConnections = true
# *.visualizer.*.displayRoutingTables = true