[General]
repeat = 5
network = src.AodvRealAdhoc5
sim-time-limit = 60s

*.host[*].ipv4.arp.typename = "GlobalArp"
*.host[*].numApps = 3
*.host[*].app[0].typename = "src.cluster.ClusterApp"
*.host[*].app[0].localPort = 4000
*.host[*].app[0].destPort  = 4000
*.host[*].app[0].helloInterval = 1s
*.host[*].app[0].cfInterval    = 3s
*.host[*].app[0].hldTimeThreshold = 1s
*.host[*].app[0].maxTrials = 3
*.host[*].app[0].requestTimeout = 1s
*.host[*].app[0].maxClusterSize = 10

#*.host[*].app[1].typename = "TcpBasicClientApp" 
*.host[*].app[1].typename = "src.tcp.RecordingTcpClientApp"
*.host[*].app[1].delaySamplePeriod = 1s
*.host[*].app[1].delayStaleWindow  = 3s
*.host[*].app[1].targetChangePeriod = 5s
*.host[*].app[1].connectPort = 1000
*.host[*].app[1].tOpen = 2s
*.host[*].app[1].tSend = 4s
*.host[*].app[1].thinkTime = 0.3s
*.host[*].app[1].idleInterval = 5s
*.host[*].app[1].sendBytes = 200B
*.host[*].app[1].sendInterval = 1s
*.host[*].app[1].connectAddress = "host[" + string((index + intuniform(1,24)) % 25) + "]"

*.host[*].app[2].typename = "TcpEchoApp"
*.host[*].app[2].localPort = 1000

*.host[*].typename = "RouterWithMetrics"
**.metrics.samplePeriod = 0.5s
**.metrics.recordPerUtility = true
*.host[*].wlan[0].typename = "WirelessInterface"

# CSMA
#*.host[*].wlan[0].mac.typename = "CsmaCaMac"
#*.host[*].wlan[0].mac.useAck = false
#*.host[*].wlan[0].mac.useRtsCts = false
#*.host[*].wlan[0].mac.useBackoff = false

#CSMA/CA
#*.host[*].wlan[0].mac.typename = "CsmaCaMac"
#*.host[*].wlan[0].mac.useAck = false
#*.host[*].wlan[0].mac.useRtsCts = false
#*.host[*].wlan[0].mac.useBackoff = true
#*.host[*].wlan[0].mac.ackTimeout = 300us

#CSMA/CA/ACK
*.host[*].wlan[0].mac.typename = "CsmaCaMac"
*.host[*].wlan[0].mac.ackTimeout = 300us
*.host[*].wlan[0].mac.useAck = true
*.host[*].wlan[0].mac.fullDuplex = false
*.host[*].wlan[0].mac.headerLength = 23B

*.host[*].wlan[0].queue.typename = "DropTailQueue"
*.host[*].wlan[0].queue.packetCapacity = 10
*.host[*].wlan[0].radio.transmitter.communicationRange = 350m
*.host[*].wlan[0].radio.receiver.ignoreInterference = false
*.host[*].wlan[0].radio.transmitter.interferenceRange = 400m
*.host[*].wlan[0].radio.typename = "UnitDiskRadio"

*.host[*].hasStatus = true
*.host[*].wlan[0].radio.energyConsumer.typename = "StateBasedEpEnergyConsumer"
*.host[*].wlan[0].radio.energyConsumer.offPowerConsumption = 0mW
*.host[*].wlan[0].radio.energyConsumer.sleepPowerConsumption = 1mW
*.host[*].wlan[0].radio.energyConsumer.switchingPowerConsumption = 1mW
*.host[*].wlan[0].radio.energyConsumer.receiverIdlePowerConsumption = 2mW
*.host[*].wlan[0].radio.energyConsumer.receiverBusyPowerConsumption = 5mW
*.host[*].wlan[0].radio.energyConsumer.receiverReceivingPowerConsumption = 10mW
*.host[*].wlan[0].radio.energyConsumer.transmitterIdlePowerConsumption = 2mW
*.host[*].wlan[0].radio.energyConsumer.transmitterTransmittingPowerConsumption = 100mW
*.host[*].energyStorage.typename = "SimpleEpEnergyStorage"
*.host[*].energyStorage.nominalCapacity = 2J # maximum capacity
*.host[*].energyStorage.initialCapacity = 2J
*.host[*].energyManagement.typename = "SimpleEpEnergyManagement"
*.host[*].energyManagement.nodeStartCapacity = 0.0001J # start threshold
*.host[*].energyManagement.nodeShutdownCapacity = 0.0001J # shutdown threshold

*.host[*].**.bitrate = 1Mbps
*.host[*].forwarding = true
#*.host[*].mobility.typename = "BonnMotionMobility"
#*.host[*].mobility.traceFile = "bonnmotion.movements"
#*.host[*].mobility.is3D = false 
#*.host[*].mobility.nodeId = -1
*.host[*].mobility.typename = "RandomWaypointMobility"
*.host[*].mobility.speed = uniform(5mps, 10mps)
*.host[*].mobility.waitTime = 100ms
*.host[*].mobility.constraintAreaMinX = 0m
*.host[*].mobility.constraintAreaMinY = 0m
*.host[*].mobility.constraintAreaMinZ = 0m
*.host[*].mobility.constraintAreaMaxX = 1250m
*.host[*].mobility.constraintAreaMaxY = 1250m
*.host[*].mobility.constraintAreaMaxZ = 0m
*.host[*].mobility.initialX = uniform(0m, 1250m)
*.host[*].mobility.initialY = uniform(0m, 1250m)
*.host[*].wlan[0].radio.displayCommunicationRange = true
#*.host[*].wlan[0].radio.displayCommunicationRange = true
#*.host[*].wlan[0].radio.displayInterferenceRange = true

#*.configurator.config = xml("<config><interface hosts='**' address='10.0.0.x' netmask='255.255.255.0'/><autoroute metric='errorRate'/></config>") 
#*.configurator.optimizeRoutes = false 
#*.host*.ipv4.routingTable.netmaskRoutes = "" 
#*.configurator.addStaticRoutes = false
*.configurator.config = xml("<config><interface hosts='**' address='10.0.0.x' netmask='255.255.255.0'/></config>")
*.configurator.addDefaultRoutes = false
*.configurator.addStaticRoutes = false
*.configurator.optimizeRoutes = false
*.host*.ipv4.routingTable.netmaskRoutes = ""

*.linkVisualizer.*.displayLinks = false
# *.visualizer.*.displayTransportConnections = true
# *.visualizer.*.displayRoutingTables = true